---
title: "ForMakingPkg"
author: "Zhenyu"
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}
library(devtools, usethis)
library(Rcpp)
```

```{r}
use_package("RcppParallel")
use_package("RcppXsimd")
use_package("Rcpp")
load_all()
check()
use_mit_license()
usethis::use_rcpp() #you have to run this command in the same directory where src/ is
document()
?rcmg
```

```{r prepare inputs}
n = 20
d = 10
mu = rep(0, d)
set.seed(666)
cov_mat = rWishart(1, 2 * d, diag(d))[ , , 1]
cor_mat = cov2cor(cov_mat)
prec = solve(cor_mat)

#cor_mat = diag(d)
#prec = diag(d)

constraits = 0
p0 = runif(d, 0, 1)
t = 2
burnin = 20
#debugSource("~/zigzag/R/hzz.R", echo=TRUE)
```

```{r to profile}
require(profvis)
profvis({res = rcmg(n, mean = mu, prec, constraits, t, burnin = as.integer(0.1 * n), p0 = p0)})
```

```{r to compare with ground truth}
require(hzz)
library(MASS)

n_hzz = 5000
debugSource("~/zigzag/R/hzz.R", echo=TRUE)
samples = rcmg(n = n_hzz, mean = mu, prec, constraits = rep(1, d), t = 1, burnin = 0, p0 = rep(0.1, d))

n_reject = 10^7
true_samples <- t(mvrnorm(n_reject, mu, cor_mat))
true_samples <- true_samples[, colSums(true_samples < 0) == 0]
print(dim(true_samples))

index <- sample(1:d, 1)

breaks <- seq(0, max(samples, true_samples) + 0.1, length=21)
hist(samples[index, ], breaks=breaks, probability=T, col=rgb(1, 0, 0, 1/4), xlim=c(0, 5))
hist(true_samples[index, ], breaks=breaks, probability=T, col=rgb(0, 0, 1, 1/4), xlim=c(0, 5), add=T)
```

```{r}
            int sign = (MathUtils.nextDouble() > 0.5) ? 1 : -1;
            momentum[i] = sign * MathUtils.nextExponential(1) * Math.sqrt(mass.get(i));
ndim = 2
momentum <- (2 * (runif(ndim) > .5) - 1) * rexp(ndim, rate = 1)
```

```{r}
source("~/truncated-normal-sampler-code/truncated-normal-sampler-code/truncated_normal_hmc.R", echo=TRUE)
f <- function (x) {
  if (length(x) == 1) {
    prec[, x]
  } else {
    drop(prec %*% x)
  }
}

t <- 1
n_samples <- 100
samples <- array(0, c(2, n_samples))

p0 = c(0.1, 0.1)
for (i in 1:n_samples) {
  #debugSource("~/truncated-normal-sampler-code/truncated-normal-sampler-code/truncated_normal_hmc.R", echo=TRUE)
  
  p0 <- truncated_normal_hmc(f, p0, mu = c(0,0), t = 1, m=NULL)
  samples[, i] <- p0
}
```
```{r}
hzz_samples = rcmg(n = n_hzz, mean = mu, prec, constraits, t = 1, burnin = 0, p0)
```



