# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create ZigZag engine object
#'
#' @param dimension the dimension of MTN (d)
#' @param lowerBounds the d-dimensional lower bound
#' @param upperBounds the d-dimensional upper bound
#' @param flags todo
#' @param info todo
#' @param seed random seed
#' @return a zigzag engine object.
#'
#' @export
createEngine <- function(dimension, lowerBounds, upperBounds, flags, info, seed) {
    .Call(`_largeMTN_createEngine`, dimension, lowerBounds, upperBounds, flags, info, seed)
}

#' Create ZigZag nuts engine object
#'
#' Helper function creates zigZag nuts engine object with given latent dimension, location count and various
#' implementation details. 
#'
#' @param dimension the dimension of MTN (d)
#' @param lowerBounds the d-dimensional lower bound
#' @param upperBounds the d-dimensional upper bound
#' @param flags todo
#' @param info todo
#' @param seed random seed
#' @param randomFlg todo
#' @param stepSize todo
#' @param mean todo
#' @param precision todo
#' @return a zigzag-nuts engine object.
#'
#' @export
createNutsEngine <- function(dimension, lowerBounds, upperBounds, flags, info, seed, randomFlg, stepSize, mean, precision) {
    .Call(`_largeMTN_createNutsEngine`, dimension, lowerBounds, upperBounds, flags, info, seed, randomFlg, stepSize, mean, precision)
}

#' Set mean for MTN
#'
#' @param sexp pointer to zigzag object
#' @param mean a numeric vector containing the MTN mean
#' @export
setMean <- function(sexp, mean) {
    invisible(.Call(`_largeMTN_setMean`, sexp, mean))
}

#' Set the precision matrix for the target MTN
#'
#' @param sexp pointer to zigzag object
#' @param precision the MTN precision matrix
#' @export
setPrecision <- function(sexp, precision) {
    invisible(.Call(`_largeMTN_setPrecision`, sexp, precision))
}

.doSomething <- function(sexp, data) {
    invisible(.Call(`_largeMTN_doSomething`, sexp, data))
}

getNextEvent <- function(sexp, position, velocity, action, logpdfGradient, momentum) {
    .Call(`_largeMTN_getNextEvent`, sexp, position, velocity, action, logpdfGradient, momentum)
}

.oneIteration <- function(sexp, position, momentum, time) {
    .Call(`_largeMTN_oneIteration`, sexp, position, momentum, time)
}

.oneNutsIteration <- function(sexp, position, momentum) {
    .Call(`_largeMTN_oneNutsIteration`, sexp, position, momentum)
}

